'\" t
.\"     Title: bluray_player
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-12-21
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BLURAY_PLAYER" "1" "2023-12-21" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
bluray_player \- play a Blu\-ray using libmpv
.SH "SYNOPSIS"
.sp
\fBbluray_player\fP [\fIPATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
The bluray_player(1) program will play a playlist from a Blu\-ray disc,
image, or directory. Playback is handled by by libmpv.
.sp
Input path can be a single filename (image), a directory, or a device name.
The default device is based on your operating system, and is the primary
optical drive.
.SH "OPTIONS"
.sp
\fB\-m, \-\-main\fP
.RS 4
Play the main playlist (default). You can see which one is the main
one using \fIbluray_info \-\-main\fP. MPV filters out duplicate playlists,
so do not use \fIbluray_info \-\-duplicates\fP as an index.
.RE
.sp
\fB\-p, \-\-playlist\fP=\fIPLAYLIST\fP
.RS 4
Play the selected playlist number.
.RE
.sp
\fB\-c, \-\-chapters\fP=\fICHAPTER[\-[CHAPTER]]\fP
Play the selected chapter range. Default is to play all chapters of
the playlist.
.sp
\fB\-a, \-\-alang\fP=\fILANGUAGE\fP
Set default audio language. Format is three\-letter language code, ISO
639\-2. For example: eng, deu, fra, spa.
.sp
\fB\-A, \-\-aid\fP=\fISTREAM ID\fP
Play audio stream ID indexed by mpv.
.sp
\fB\-s, \-\-slang\fP=\fILANGUAGE\fP
Display subtitles for selected language, if available.
.sp
\fB\-S, \-\-sid\fP=\fISTREAM ID\fP
Play subtitle stream ID indexed by mpv.
.sp
\fB\-V, \-\-vid\fP=\fISTREAM ID\fP
Play video stream ID indexed by mpv (default: first).
.sp
\fB\-f, \-\-fullscreen\fP
Display video in fullscreen.
.sp
\fB\-d, \-\-deinterlace\fP
Deinterlace video during playback.
.sp
\fB\-k, \-\-keydb\fP=\fIFILENAME\fP
Location to \fIKEYDB.cfg\fP used by libaacs for decryption. Default is
\fI~/.config/aacs/KEYDB.cfg\fP
.sp
\fB\-h, \-\-help\fP
Display help output.
.sp
\fB\-\-version\fP
Display version information.
.SH "CONFIGURATION"
.sp
bluray_player(1) uses libmpv as the engine for playback (see
\c
.URL "https://mpv.io/" "" ")."
Configuration for bluray_player is stored in
~/.config/bluray_player/mpv.conf and will be read on each time during startup.
.sp
Passing options to \fIbluray_player\fP will override the configuration file.
.sp
See mpv(1) for all configuration options.
.SH "SEE ALSO"
.sp
bluray_info(1), bluray_copy(1), mpv(1)
.SH "BUGS"
.sp
\fBbluray_player\fP does not wait for an optical device to be ready. Wait for it to
finish "polling" before running the program.
.sp
Please file bugs at \c
.URL "https://github.com/beandog/bluray_info/issues" "" ""
.SH "AUTHOR"
.sp
bluray_player was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/bluray_info" "" ""
.sp
Main web site: \c
.URL "https://dvds.beandog.org" "" ""
.SH "COPYING"
.sp
Copyright (C) 2019 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).