.TH BLURAY_INFO 1 "2018-12-27" "1.5" "Blu-ray utilities"
.SH NAME
bluray_info \- display Blu-ray information
.SH SYNOPSIS
.B bluray_info
[\fIpath\fR] [\fIoptions\fR]
.SH DESCRIPTION
.B bluray_info
displays detailed information about a Blu-ray, such as its audio and video streams, chapters, subtitles in multiple output formats.
.TP
Input path can be a device, a filename, or directory.
.TP
Default output is summarized human-readable format of all titles.
.SH OPTIONS
.TP
Display extra information:
.TP
.BR \-v ", " \-\-video
Display video tracks, codec, format, aspect ratio, and framerate.
.TP
.BR \-a ", " \-\-audio
Display audio tracks, language, codec, format, and channel rate.
.TP
.BR \-s ", " \-\-subtitles
Display subtitle tracks and language.
.TP
.BR \-c ", " \-\-chapters
Display chapter indexes, starting time, and duration.
.TP
.BR \-x ", " \-\-all
Display all of the above.
.TP
Results can be limited by matching certain criteria:
.TP
.BR \-A ", " \-\-has-audio
Only display titles that have audio tracks.
.TP
.BR \-S ", " \-\-has-subtitles
Only display titles that have subtitles.
.TP
.BI \-E\  number \fR,\ \fB\-\-seconds\  number
Title has a minimum number of seconds.
.TP
.BI \-E\  number \fR,\ \fB\-\-minutes\  number
Title has a minimum number of minutes (cannot be combined with seconds).
.TP
Display can be limited to a specific title or playlist:
.TP
.BR \-m ", " \-\-main
Limit to main title as designated by libbluray. This is not necessarily the longest title or the one that is the main feature.
.TP
.BI \-t\  number \fR,\ \ft\-\-title\  number
Limit to selected title.
.TP
.BI \-p\  number \fR,\ \ft\-\-playlist\  number
Limit to selected playlist.
.TP
.BR \-j ", " \-\-json
Display output in JSON format. Useful for scripting. The JSON output includes much more information than the human-readable output does.
.TP
.BR \-i ", " \-\-id
Display the Blu-ray's alphanumeric ID of 40 characters, if available. Not all discs have this, so it is not safe to use as a unique identifier. Requires AACS (DRM) to be present on Blu-ray.
.TP
.BR \-n ", " \-\-name
Display the Blu-ray's name, if it set.
.TP
.BR \-u ", " \-\-volname
Display the disc's UDF volume name.
Input path must be a disc device or single file.
.TP
.BR \-d ", " \-\-xchap
Display chapters in an export format compatible with muxing applications such as ogmmerge and mkvmerge.
.TP
.BR -\q ", " \-\-quiet
Quiet mode. Trim the "Disc title" header and "Main title" footer from human-readable output format.
.TP
libaacs:
.TP
.BI \-k\  filename \fR,\ \fB\-\-keydb\  filename
Specify location of KEYDB.cfg file if disc has AACS DRM. libaacs uses ~/.config/aacs/KEYDB.cfg by default.
.SH NOTES
.TP
Blu-ray video display sizes and formats:
.TP
.BR 480i
.RS
480 pixels in height of interlaced video.
.RE
.TP
.BR 480p
.RS
480 pixels in height of progressive video.
.RE
.TP
.BR 576i
.RS
576 pixels in height of interlaced video.
.RE
.TP
.BR 576p
.RS
576 pixels in height of progressive video.
.RE
.TP
.BR 720p
.RS
720 pixels in height of progressive video.
.RE
.TP
.BR 1080i
.RS
1080 pixels in height of interlaced video.
.RE
.TP
.BR 1080p
.RS
1080 pixels in height of progressive video.
.RE
.TP
.BR 2160p
.RS
2160 pixels in height of progressive video. Also known as 4K.
.RE
.TP
Blu-ray video codecs:
.TP
.BR h264
.RS
H.264 / MPEG-4 Part 10 / AVC (Advanced Video Codec)
.RE
.TP
.BR h265
.RS
H.265 / MPEG-H Part 2 / HEVC (High Efficiency Video Codec)
.RE
.TP
.BR mpeg1
.RS
MPEG-1 Part 2
.RE
.TP
.BR mpeg2
.RS
MPEG-2 Part 2
.RE
.TP
.BR vc1
.RS
SMPTE 421M
.RE
.TP
Blu-ray video framerates:
.TP
Possible FPS (frames per second) values are 23.97 (24000/1001), 24, 25, 29.97 (30000/1001), 50, and 59.94 (60000/1001).
.TP
Blu-ray audio codecs:
.TP
.BR ac3
.RS
Dolby Digital / DD / ATSC / A/52
.RE
.TP
.BR ac3plus
.RS
Dolby Digital Plus / Enhanced AC-3 / DD+ / E-AC-3
.RE
.TP
.BR truhd
.RS
Dolby TrueHD
.RE
.TP
.BR dts
.RS
DTS / Digital Theater Systems / DCA
.RE
.TP
.BR dtshd
.RS
DTS-HD
.RE
.TP
.BR dtshd-ma
.RS
DTS-HD Master Audio / DTS++
.RE
.TP
.BR lpcm
.RS
Linear PCM / Linear pulse-code modulation
.RE
.TP
.BR mpeg1
.RS
MPEG-1
.RE
.TP
.BR mpeg2
.RS
MPEG-2 / MP2
.RE
.TP
Blu-ray subtitles:
.TP
All subtitles are PGS format - Presentation Graphic Stream.
.TP
Blu-ray DRM (Digital Rights Management):
.TP
Discs with AACS (Advanced Access Content System) uses libaacs to decrypt content if libbluray is compiiled wih support for it.
.SH DEFAULTS
.TP
Display output is summarized human-readable format of all titles.
.TP
JSON output displays all titles.
.TP
Chapter export format displays the main title.
.TP
Looks for KEYDB.cfg file in ~/.config/aacs/KEYDB.cfg
.TP
Input path is the Blu-ray drive based on the operating system: Linux /dev/sr0, DragonFly BSD and FreeBSD /dev/cd0, NetBSD /dev/cd0d, OpenBSD /dev/rcd0c, Mac /dev/disk1.
.SH LICENSE
.B bluray_info
is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.SH AUTHORS
.B bluray_info
was written by Steve Dibb <steve.dibb@gmail.com>
.SH "SEE ALSO"
.BR bluray_copy (1)
