#ifndef BLURAY_INFO_H
#define BLURAY_INFO_H

#define BLURAY_ID 40
#define BLURAY_TITLE 32
#define BLURAY_VIDEO_CODEC 5
#define BLURAY_VIDEO_FORMAT 5
#define BLURAY_VIDEO_FRAMERATE 6
#define BLURAY_VIDEO_ASPECT_RATIO 4
#define BLURAY_AUDIO_LANG 3

#endif
