'\" t
.\"     Title: bluray_copy
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.23
.\"      Date: 2025-06-10
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BLURAY_COPY" "1" "2025-06-10" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
bluray_copy \- copy a title or playlist from a Blu\-ray to a file or stdout
.SH "SYNOPSIS"
.sp
\fBbluray_copy\fP [\fIPATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
The bluray_copy(1) program will copy a playlist from a Blu\-ray disc, image,
or directory to either a file or stdout.
.sp
Input path can be a single filename (image), a directory, or a device name.
The default device is based on your operating system, and is the primary
optical drive.
.sp
Default output filename is \fIbluray_playlist_#.m2ts\fP where the number is
a zero\-padded string of the main playlist.
.SH "OPTIONS"
.sp
\fB\-m, \-\-main\fP
.RS 4
Copy the main playlist (default).
.RE
.sp
\fB\-p, \-\-playlist\fP \fIPLAYLIST\fP
.RS 4
Copy the selected playlist number.
.RE
.sp
\fB\-c, \-\-chapter\fP \fICHAPTER[\-CHAPTER]\fP
Copy the selected chapter or range range. Default is to copy all
chapters.
.sp
\fB\-o, \-\-output\fP \fIFILENAME\fP
Save to filename. Default is \fIbluray_playlist_#.m2ts\fP.
.sp
.if n .RS 4
.nf
.fam C
\*(AqFILENAME\*(Aq can be \*(Aq\-\*(Aq to send to standard output. All display output
is switched to standard error output.
.fam
.fi
.if n .RE
.sp
\fB\-k, \-\-keydb\fP \fIFILENAME\fP
Location to \fIKEYDB.cfg\fP used by libaacs for decryption. Default is
\fI~/.config/aacs/KEYDB.cfg\fP.
.sp
\fB\-a, \-\-angle\fP \fIANGLE\fP
Video angle number. Default is the first.
.sp
\fB\-d, \-\-duplicates\fP
Select from index of duplicate titles that libbluray would originally
filter out. Recommended to use this for consistency across environments.
.sp
\fB\-h, \-\-help\fP
Display help output.
.sp
\fB\-\-version\fP
Display version information.
.SH "SEE ALSO"
.sp
bluray_info(1), bluray_player(1), bluray_backup(1), bluray_rip(1)
.SH "BUGS"
.sp
\fBbluray_copy\fP does not wait for an optical device to be ready. Wait for it to
finish "polling" before running the program.
.sp
Please file bugs at \c
.URL "https://github.com/beandog/bluray_info/issues" "" ""
.SH "AUTHOR"
.sp
bluray_copy was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/bluray_info" "" ""
.sp
Main web site: \c
.URL "https://dvds.beandog.org" "" ""
.SH "COPYING"
.sp
Copyright (C) 2019 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).