'\" t
.\"     Title: bluray_info
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-12-12
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BLURAY_INFO" "1" "2023-12-12" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
bluray_info \- displays information about a Blu\-ray
.SH "SYNOPSIS"
.sp
\fBbluray_info\fP [\fIPATH\fP] [\fIOPTIONS\fP]
.SH "DESCRIPTION"
.sp
The bluray_info(1) program displays information about a Blu\-ray disc, image,
or directory in human\-readable, JSON, or formatted chapter outputs.
.sp
Input path can be a single filename (image), a directory, or a device name.
The default device is based on your operating system, and is the primary
optical drive.
.SH "OPTIONS"
.sp
\fB\-m, \-\-main\fP
.RS 4
Display only the main title / playlist as defined by the metadata. By
default, bluray_info will display all titles.
.RE
.sp
\fB\-t, \-\-title\fP=\fITITLE\fP
.RS 4
Limit output to the selected title.
.RE
.sp
\fB\-p, \-\-playlist\fP=\fIPLAYLIST\fP
.RS 4
Limit output to selected playlist.
.RE
.sp
\fB\-k, \-\-keydb\fP=\fIFILE\fP
.RS 4
Location to \fIKEYDB.cfg\fP used by libaacs for decryption. Default is
\fI~/.config/aacs/KEYDB.cfg\fP.
.RE
.sp
\fB\-v, \-\-video\fP
.RS 4
Display detailed information about video streams.
.RE
.sp
\fB\-a, \-\-audio\fP
.RS 4
Display detailed information about audio streams.
.RE
.sp
\fB\-s, \-\-subtitles\fP
.RS 4
Display detailed information about subtitles.
.RE
.sp
\fB\-c, \-\-chapters\fP
.RS 4
Display detailed information about chapters.
.RE
.sp
\fB\-x, \-\-all\fP
.RS 4
Display all optional detailed information.
.RE
.sp
\fB\-d, \-\-duplicates\fP
.RS 4
Display duplicate titles that libbluray would originally filter out
.RE
.sp
\fB\-j, \-\-json\fP
.RS 4
Format output in JSON. All detailed information is included.
.RE
.sp
\fB\-A, \-\-has\-audio\fP
.RS 4
Limit output to titles that have audio tracks.
.RE
.sp
\fB\-S, \-\-has\-subtitles\fP
.RS 4
Limit output to titles that have subtitles.
.RE
.sp
\fB\-N, \-\-has\-alang\fP=\fILANGUAGE\fP
.RS 4
Limit output to titles that have an audio stream of a specific
language (examples: eng, fra, spa).
.RE
.sp
\fB\-G, \-\-has\-slang\fP=\fILANGUAGE\fP
.RS 4
Limit output to titles that have a subtitle of a specific language
(examples: eng, fra, spa).
.RE
.sp
\fB\-E, \-\-seconds\fP=\fISECONDS\fP
.RS 4
Limit output to titles with a minimum length of number of seconds.
.RE
.sp
\fB\-M, \-\-minutes\fP=\fIMINUTES\fP
.RS 4
Limit output to titles with a minimum length of number of minutes.
Cannot be used in combination with \fI\-\-seconds\fP.
.RE
.sp
\fB\-g, \-\-xchap\fP
.RS 4
Display title chapters in export format suitable for mkvmerge(1) and
ogmmerge(1). See also dvdxchap(1) for details on format syntax.
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Display help output.
.RE
.sp
\fB\-\-version\fP
.RS 4
Display version information.
.RE
.SH "SEE ALSO"
.sp
bluray_copy(1), bluray_player(1)
.SH "BUGS"
.sp
\fBbluray_info\fP does not wait for an optical device to be ready. Wait for it to
finish "polling" before running the program.
.sp
Some discs fail to be opened if they have encryption that libaacs cannot read.
.sp
Please file bugs at \c
.URL "https://github.com/beandog/bluray_info/issues" "" ""
.SH "AUTHOR"
.sp
bluray_info was written by Steve Dibb \c
.MTO "steve.dibb\(atgmail.com" "" ""
.SH "RESOURCES"
.sp
Source code available at GitHub: \c
.URL "https://github.com/beandog/bluray_info" "" ""
.sp
Main web site: \c
.URL "https://dvds.beandog.org" "" ""
.SH "COPYING"
.sp
Copyright (C) 2019 Steve Dibb. Free use of this software is granted under the
terms of the GNU General Public License, version 2 (GPL).